--------------------------------------------------------
--  File created - Monday-March-13-2023   
--------------------------------------------------------
DROP TABLE "SANA"."CHERCHEURS";
DROP TABLE "SANA"."COMMANDES";
DROP TABLE "SANA"."EMPLOYES";
DROP TABLE "SANA"."EVENEMENTS";
DROP TABLE "SANA"."MATERIELS";
DROP TABLE "SANA"."PARTICIPANTS";
DROP TABLE "SANA"."PUBLICATIONS";
--------------------------------------------------------
--  DDL for Sequence CHERCHEURS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."CHERCHEURS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CHERCHEURS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."CHERCHEURS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."EMPLOYE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVENEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."EVENEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MATERIELS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."MATERIELS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARTICIPANTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."PARTICIPANTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PUBLICITE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SANA"."PUBLICITE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CHERCHEURS
--------------------------------------------------------

  CREATE TABLE "SANA"."CHERCHEURS" 
   (	"ID_CHERCHEUR" NUMBER(11,0), 
	"CIN_CHERCHEUR" NUMBER(11,0), 
	"NOM_CHERCHEUR" VARCHAR2(20 BYTE), 
	"PRENOM_CHERCHEUR" VARCHAR2(20 BYTE), 
	"AGE_CHERCHEUR" NUMBER(2,0), 
	"TELEPHONE_CHERCHEUR" NUMBER(11,0), 
	"EMAIL_CHERCHEUR" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "SANA"."COMMANDES" 
   (	"ID_EMP" NUMBER(11,0), 
	"ID_MATERIEL" NUMBER(11,0), 
	"DATE_ACHAT" VARCHAR2(8 BYTE), 
	"QUANTITE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "SANA"."EMPLOYES" 
   (	"ID_EMP" NUMBER(11,0), 
	"CIN_EMP" NUMBER(11,0), 
	"NOM_EMP" VARCHAR2(20 BYTE), 
	"COLUMN3" VARCHAR2(20 BYTE), 
	"COLUMN4" NUMBER(3,0), 
	"POSTE" VARCHAR2(20 BYTE), 
	"TELEPHONE_EMP" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENTS
--------------------------------------------------------

  CREATE TABLE "SANA"."EVENEMENTS" 
   (	"ID_EVENT" NUMBER(11,0), 
	"NOM_EVENT" VARCHAR2(20 BYTE), 
	"DATE_DEBUT_EVENT" VARCHAR2(8 BYTE), 
	"DATE_FIN_EVENT" VARCHAR2(8 BYTE), 
	"LIEU_EVENT" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIELS
--------------------------------------------------------

  CREATE TABLE "SANA"."MATERIELS" 
   (	"ID_MATERIEL" NUMBER(11,0), 
	"NOM_MATEREIL" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"COLUMN4" NUMBER(20,0), 
	"DATE_EXPIRATION" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "SANA"."PARTICIPANTS" 
   (	"ID_EMP" NUMBER(11,0), 
	"ID_CHERCHEUR" NUMBER(11,0), 
	"ID_EVENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLICATIONS
--------------------------------------------------------

  CREATE TABLE "SANA"."PUBLICATIONS" 
   (	"ID_PUB" NUMBER(11,0), 
	"TITRE" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(8 BYTE), 
	"COLUMN3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SANA.CHERCHEURS
SET DEFINE OFF;
Insert into SANA.CHERCHEURS (ID_CHERCHEUR,CIN_CHERCHEUR,NOM_CHERCHEUR,PRENOM_CHERCHEUR,AGE_CHERCHEUR,TELEPHONE_CHERCHEUR,EMAIL_CHERCHEUR) values (49,122,'EEE','ZZZ',2,12345,'sss44@HYGFVG.EEEEE');
Insert into SANA.CHERCHEURS (ID_CHERCHEUR,CIN_CHERCHEUR,NOM_CHERCHEUR,PRENOM_CHERCHEUR,AGE_CHERCHEUR,TELEPHONE_CHERCHEUR,EMAIL_CHERCHEUR) values (50,666,'tzest','test',4,233,'hgjvfh@hgc.hhh');
REM INSERTING into SANA.COMMANDES
SET DEFINE OFF;
REM INSERTING into SANA.EMPLOYES
SET DEFINE OFF;
REM INSERTING into SANA.EVENEMENTS
SET DEFINE OFF;
REM INSERTING into SANA.MATERIELS
SET DEFINE OFF;
REM INSERTING into SANA.PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into SANA.PUBLICATIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CHERCHEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."CHERCHEURS_PK" ON "SANA"."CHERCHEURS" ("ID_CHERCHEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."COMMANDES_PK" ON "SANA"."COMMANDES" ("ID_EMP", "ID_MATERIEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."EMPLOYES_PK" ON "SANA"."EMPLOYES" ("ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."EVENEMENT_PK" ON "SANA"."EVENEMENTS" ("ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."MATERIELS_PK" ON "SANA"."MATERIELS" ("ID_MATERIEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTICIPANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."PARTICIPANTS_PK" ON "SANA"."PARTICIPANTS" ("ID_EMP", "ID_CHERCHEUR", "ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PUBLICITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SANA"."PUBLICITE_PK" ON "SANA"."PUBLICATIONS" ("ID_PUB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CHERCHEURS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."CHERCHEURS_TRG" 
BEFORE INSERT ON CHERCHEURS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CIN_CHERCHEUR IS NULL THEN
      SELECT CHERCHEURS_SEQ.NEXTVAL INTO :NEW.CIN_CHERCHEUR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."CHERCHEURS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHERCHEURS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."CHERCHEURS_TRG1" 
BEFORE INSERT ON CHERCHEURS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CHERCHEUR IS NULL THEN
      SELECT CHERCHEURS_SEQ1.NEXTVAL INTO :NEW.ID_CHERCHEUR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."CHERCHEURS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMANDES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."COMMANDES_TRG" 
BEFORE INSERT ON COMMANDES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."COMMANDES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."EMPLOYE_TRG" 
BEFORE INSERT ON EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMP IS NULL THEN
      SELECT EMPLOYE_SEQ.NEXTVAL INTO :NEW.ID_EMP FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."EMPLOYE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENEMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."EVENEMENT_TRG" 
BEFORE INSERT ON EVENEMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EVENT IS NULL THEN
      SELECT EVENEMENT_SEQ.NEXTVAL INTO :NEW.ID_EVENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."EVENEMENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MATERIELS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."MATERIELS_TRG" 
BEFORE INSERT ON MATERIELS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_MATERIEL IS NULL THEN
      SELECT MATERIELS_SEQ.NEXTVAL INTO :NEW.ID_MATERIEL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."MATERIELS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PARTICIPANTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."PARTICIPANTS_TRG" 
BEFORE INSERT ON PARTICIPANTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMP IS NULL THEN
      SELECT PARTICIPANTS_SEQ.NEXTVAL INTO :NEW.ID_EMP FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."PARTICIPANTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PUBLICITE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SANA"."PUBLICITE_TRG" 
BEFORE INSERT ON PUBLICATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PUB IS NULL THEN
      SELECT PUBLICITE_SEQ.NEXTVAL INTO :NEW.ID_PUB FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SANA"."PUBLICITE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CHERCHEURS
--------------------------------------------------------

  ALTER TABLE "SANA"."CHERCHEURS" ADD CONSTRAINT "CHERCHEURS_CHK1" CHECK (EMAIL_CHERCHEUR LIKE '%_@%_._%') ENABLE;
  ALTER TABLE "SANA"."CHERCHEURS" ADD CONSTRAINT "CHERCHEURS_PK" PRIMARY KEY ("ID_CHERCHEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."CHERCHEURS" MODIFY ("ID_CHERCHEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "SANA"."COMMANDES" ADD CONSTRAINT "COMMANDES_PK" PRIMARY KEY ("ID_EMP", "ID_MATERIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."COMMANDES" MODIFY ("ID_MATERIEL" NOT NULL ENABLE);
  ALTER TABLE "SANA"."COMMANDES" MODIFY ("ID_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SANA"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."EMPLOYES" MODIFY ("ID_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENTS
--------------------------------------------------------

  ALTER TABLE "SANA"."EVENEMENTS" ADD CONSTRAINT "EVENEMENT_PK" PRIMARY KEY ("ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."EVENEMENTS" MODIFY ("ID_EVENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIELS
--------------------------------------------------------

  ALTER TABLE "SANA"."MATERIELS" ADD CONSTRAINT "MATERIELS_PK" PRIMARY KEY ("ID_MATERIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."MATERIELS" MODIFY ("NOM_MATEREIL" NOT NULL ENABLE);
  ALTER TABLE "SANA"."MATERIELS" MODIFY ("ID_MATERIEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "SANA"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_PK" PRIMARY KEY ("ID_EMP", "ID_CHERCHEUR", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."PARTICIPANTS" MODIFY ("ID_EVENT" NOT NULL ENABLE);
  ALTER TABLE "SANA"."PARTICIPANTS" MODIFY ("ID_CHERCHEUR" NOT NULL ENABLE);
  ALTER TABLE "SANA"."PARTICIPANTS" MODIFY ("ID_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "SANA"."PUBLICATIONS" ADD CONSTRAINT "PUBLICITE_PK" PRIMARY KEY ("ID_PUB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SANA"."PUBLICATIONS" MODIFY ("ID_PUB" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "SANA"."COMMANDES" ADD CONSTRAINT "COMMANDES_FK1" FOREIGN KEY ("ID_EMP")
	  REFERENCES "SANA"."EMPLOYES" ("ID_EMP") ENABLE;
  ALTER TABLE "SANA"."COMMANDES" ADD CONSTRAINT "COMMANDES_FK2" FOREIGN KEY ("ID_EMP")
	  REFERENCES "SANA"."MATERIELS" ("ID_MATERIEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "SANA"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_FK1" FOREIGN KEY ("ID_CHERCHEUR")
	  REFERENCES "SANA"."CHERCHEURS" ("ID_CHERCHEUR") ENABLE;
  ALTER TABLE "SANA"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_FK2" FOREIGN KEY ("ID_EMP")
	  REFERENCES "SANA"."EMPLOYES" ("ID_EMP") ENABLE;
  ALTER TABLE "SANA"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_FK3" FOREIGN KEY ("ID_EVENT")
	  REFERENCES "SANA"."EVENEMENTS" ("ID_EVENT") ENABLE;
